import { useState } from 'react'
import './App.css'

function App() {

  const [input, setInput] = useState('');
  const [response, setResponse] = useState('');
  const [imageUrl, setImageUrl] = useState('');
  const [uploadedImage, setUploadedImage] = useState<File | null>(null);

  const handleSend = async () => {
    const formData = new FormData();
    formData.append('message', input); // Add the text input
    if (uploadedImage) {
      formData.append('image', uploadedImage); // Add the uploaded image
    }

    const res = await fetch('http://localhost:3000/prompt', {
      method: 'POST',
      body: formData, // Send FormData
    });
    const data = await res.json();
    setResponse(data.choices?.[0]?.message?.content || 'No response');
    setImageUrl(data.imageUrl || '');
  };

  const handleImageUpload = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (file) {
      setUploadedImage(file);
    }
  };

  return (
    <>
      <input
        value={input}
        onChange={e => setInput(e.target.value)}
        placeholder="Ask ChatGPT..."
      />
      <button onClick={handleSend}>Send</button>
      <div>{response}</div>
      {imageUrl && <img src={imageUrl} alt="Generated by AI" />}
      <input type="file" accept="image/png" onChange={handleImageUpload} />
      {uploadedImage && <p>Uploaded Image: {uploadedImage.name}</p>}
    </>
  )
}

export default App
